language: python
python:
  - "2.7"
services:
  - elasticsearch
before_script:
  - sleep 10
install:
  - pip install -r requirements-ci.txt
script: python manage.py test -v 2
env:
  - ELASTICSEARCH_URL=http://127.0.0.1:9200/

