language: python
cache: pip
python:
  - "2.7"
services:
  - elasticsearch
before_script:
  - sleep 10
install:
  - pip install -r requirements-ci.txt
script:
  - coverage run --source='.' manage.py test -v 2
  - coverage report
after_success:
  - coveralls
env:
  - ELASTICSEARCH_URL=http://127.0.0.1:9200/
  - COVERALLS_REPO_TOKEN=e4x1YSoHzZd9c7lmIu880ghTMniH24YLq
