
mysql:
    image: mysql:latest
    volumes_from:
        - data
    environment:
        MYSQL_ROOT_PASSWORD: drummer01
        MYSQL_DATABASE: tola_activity
        MYSQL_USER: glind
        MYSQL_PASSWORD: drummer01
  restart: always
nginx:
   image: nginx
   restart: always
   volumes:
      - .:/home/TolaActivity
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/activity.toladata.io/fullchain.pem:/etc/letsencrypt/live/activity.toladata.io/fullchain.pem
      - /etc/letsencrypt/live/activity.toladata.io/privkey.pem:/etc/letsencrypt/live/activity.toladata.io/privkey.pem
   ports:
      - "80:80"
      - "443:443"
   links:
      - tola
tola:
   build: .
   restart: always
#   command: bash -c 'python manage.py migrate && python manage.py runserver 0.0.0.0:8000'
   command: bash -c 'python manage.py runscript workflow_migration  && python manage.py runserver 0.0.0.0:8000'
   volumes:
       - .:/code
   expose:
       - "8000"
   links: